export enum ErrorEnum {
    NotFound = 'Not found',
    EmailUsed = 'This email is available',
    RoleId = 'The role_id was entered incorrectly',
    CreateNotAdmin = 'Create not admin',
    NotFoundLogin = 'Incorrect login information',
    FailedToCreateAd = 'Failed to create advertisement',
    FailedToCreateMovies = 'Failed to create movies',
    FailedToCreateRole = 'Failed to create role',
    FailedToCreateSeries = 'Failed to create series',
    FailedToCreateStatistics = 'Failed to create FailedToCreateStatistics',
    invalidData = 'Incorrect information !',
    Unauthorized = 'Unauthorized',
    equalPasswords = 'password is incorrect',
}